version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      MONGO_URI: mongodb://db:27017/mongodb
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
